language: c
sudo: false

addons:
  apt:
    packages:
    - libgmp-dev

cache:
  directories:
  - $HOME/.stack

# Handle git submodules ourselves
git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - chmod a+x ~/.local/bin/stack

install:
  - stack setup
  - stack build --only-snapshot
  - stack install hindent
  - stack install cabal-install

script:
  - git --version
  - stack --version
  - travis_wait 120 ./zift.hs run
