name: intray-client-gen
version: '0.0.0.0'
synopsis: Intray Client Generators
category: Intray
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2016-2018 Tom Sydney Kerckhove'
license: AllRightsReserved
github: NorfairKing/intray
default-extensions:
- NoImplicitPrelude

library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Intray.Client.Gen
  
  dependencies:
  - QuickCheck
  - base >=4.7 && <5
  - genvalidity
  - genvalidity-containers
  - intray-client
  - intray-data-gen

tests:
  intray-client-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck
    - base
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - hspec
    - intray-client
    - intray-client-gen
    - intray-data-gen
