name: intray-data-gen
version: '0.0.0.0'
synopsis: Generators for intray-data
category: Intray
author: Tom Sydney Kerckhove
maintainer: syd.kerckhove@gmail.com
copyright: ! 'Copyright: (c) 2017 Tom Sydney Kerckhove'
license: AllRightsReserved
github: NorfairKing/intray-server
default-extensions:
- NoImplicitPrelude

library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Intray.Data.Gen

  dependencies:
  - QuickCheck >=2.9
  - base >=4.7 && <5
  - bytestring
  - genvalidity >=0.4 && <0.5
  - genvalidity-bytestring >=0.1 && <0.2
  - genvalidity-text >=0.4 && <0.5
  - genvalidity-time >=0.1 && <0.2
  - genvalidity-uuid >=0.0 && <0.1
  - intray-api
  - intray-data
  - text
  - validity
  - validity-bytestring
  - validity-text
  - validity-time

tests:
  intray-data-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-text
    - hspec
    - intray-api
    - intray-data
    - intray-data-gen
    - QuickCheck
    - text
    - bytestring
